name: unit-test

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check test results
        run: |
          # Check the exit code of the test command
          if [ ${{ steps.build.outcome }} == 'failure' ]; then
            echo "Tests failed. Please fix the failing tests before merging."
            exit 1
          else
            echo "Tests passed."
          fi
